# Generated by Django 4.0 on 2024-03-07 05:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_userdata_id_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='generated_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='generated_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
